name: deploy
on:
  push:
#    branches:
#      - main

jobs:
  build-deploy:
    timeout-minutes: 3
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: install packages
        run: bun install
      - name: build
        run: bun run build
      - name: publish to Cloudflare Page
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "portfolio"
          directory: "./dist"
          wranglerVersion: '3'