name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  check-format:
    timeout-minutes: 3
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: install packages
        run: bun install
      - name: check format
        run: bun run format:check

